#!/bin/bash

set -u

# The following symbols (past the first nine) are taken from tegra.h.

FUNCS=$($NM -D --format=bsd --defined-only ${1-.libs/libdrm_tegra.so} | awk '{print $3}'| while read func; do
( grep -q "^$func$" || echo $func )  <<EOF
__bss_end__
__bss_start__
__bss_start
__end__
_bss_end__
_edata
_end
_fini
_init
drm_tegra_bo_get_flags
drm_tegra_bo_get_handle
drm_tegra_bo_get_tiling
drm_tegra_bo_map
drm_tegra_bo_new
drm_tegra_bo_ref
drm_tegra_bo_set_flags
drm_tegra_bo_set_tiling
drm_tegra_bo_unmap
drm_tegra_bo_unref
drm_tegra_bo_wrap
drm_tegra_close
drm_tegra_new
drm_tegra_channel_open
drm_tegra_channel_close
drm_tegra_job_new
drm_tegra_job_free
drm_tegra_job_submit
drm_tegra_pushbuf_new
drm_tegra_pushbuf_free
drm_tegra_pushbuf_prepare
drm_tegra_pushbuf_relocate
drm_tegra_pushbuf_sync
drm_tegra_fence_wait_timeout
drm_tegra_fence_free
drm_tegra_bo_get_name
drm_tegra_bo_from_name
drm_tegra_bo_from_dmabuf
drm_tegra_bo_to_dmabuf
drm_tegra_bo_get_size
drm_tegra_bo_forbid_caching
EOF
done)

test ! -n "$FUNCS" || echo $FUNCS
test ! -n "$FUNCS"
